sudo: required
dist: xenial
language: cpp
compiler: gcc
install:
  - sudo apt-add-repository "deb http://archive.ubuntu.com/ubuntu xenial-backports main restricted universe multiverse"
  - sudo apt-add-repository "deb http://mirror.openio.io/pub/repo/openio/sds/16.10/ubuntu xenial/"
  - sudo apt-get update -qq
  - sudo apt-get install -y ragel protobuf-compiler libprotobuf-dev liberasurecode-dev attr libattr1 libattr1-dev
  - sudo apt-get install -y maven
  - pip install --upgrade pip cpplint
script:
  - set -e
  - cmake -DCMAKE_INSTALL_PREFIX=/tmp/oio -DCMAKE_BUILD_TYPE=Release -DSYS=OFF .
  - make all
  - nohup java -jar 3rd/kinetic-java/kinetic-simulator/target/kinetic-simulator-3.0.7-SNAPSHOT-jar-with-dependencies.jar 2>/dev/null >/dev/null &
  - make -C tests/unit test
  - make -C tests/func test
